blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.home_blog, name='home-blog'),
    path('category/<str:category_name>/', views.home_blog, name='category-page'),
    path('tag/<str:tag_name>/', views.home_blog, name='tag-page'),
    path('author/<str:author_username>/', views.home_blog, name='author-page'),
    path('search/', views.blog_search, name='blog-search'),
    path('tag_test/', views.tag_test),
    path('<slug:slug>/', views.single_blog, name='single-blog'),



]

core/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from mysite.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog" : BlogSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mysite.urls')),
    path('blog/', include('blog.urls')),
    path("accounts/", include("users.urls")),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",
),

    path('robots.txt', include('robots.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.urls import path
from mysite import views

app_name = 'mysite'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('sitemap/', views.sitemap, name='sitemap'),
    path('subscribe/', views.subscibe, name='subscibe'),
    path('test2/', views.test2, name='test2'),

]

blog/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify



class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    image = models.ImageField(upload_to='media/', null=True, blank=True)
    author = models.ForeignKey(to='users.SiteAdmin', on_delete=models.PROTECT, null=True, blank=True)
    category = models.ManyToManyField(to='blog.Category', blank=True)
    tag = models.ForeignKey(to='blog.Tag', on_delete=models.SET_NULL, null=True)
    published_date = models.DateTimeField()
    slug = models.SlugField(null=True, blank=True, unique=True)
    view_count = models.PositiveIntegerField(default=0)
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ("-published_date",)

    def __str__(self):
        return "{} - {}".format(self.title, self.id)
    
    def get_absolute_url(self):
        return reverse("blog:single-blog", kwargs={"slug": self.slug})
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name} ---> id: {self.id}"

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post
from django.utils import timezone
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def home_blog(request, **kwargs):
    current_time =timezone.now()
    posts = Post.objects.filter(published_date__lte=current_time, status=True)
    if kwargs.get('category_name'):
        posts = posts.filter(category__name=kwargs['category_name'])
    elif kwargs.get('tag_name'):
        posts = posts.filter(tag__name=kwargs['tag_name'])
    elif kwargs.get('author_username'):
        posts = posts.filter(author__username=kwargs['author_username'])

    posts = Paginator(posts, 4)
    try :
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
        page_range = posts.paginator.page_range
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(posts.num_pages)
    context = {'posts': posts, 'page_range': page_range}
    return render(request, 'blog/blog-home.html', context)     

def single_blog(request, slug):

    current_time =timezone.now()
    published_posts = Post.objects.filter(published_date__lte=current_time, status=True)
    post = get_object_or_404(published_posts, slug=slug)
    next_post = published_posts.filter(published_date__gt=post.published_date).order_by('published_date').first()
    previous_object = published_posts.filter(published_date__lt=post.published_date).order_by('-published_date').first()

    # increase view_count
    post.view_count += 1
    post.save()

    context = {'post': post, 'next_post':next_post, 'previous_object':previous_object}
    return render(request, 'blog/blog-single.html', context)

def test(request):
    current_time =timezone.now()
    posts = Post.objects.filter(status=True, published_date__lte=current_time)
    current = None
    archive = {}
    for post in posts:
        year = post.published_date.year
        if current != year:
            current = year
            archive[year] = [post]
        else:
            archive[year].append(post)
    context = {'archive':archive}
    return render(request, 'test.html', context)


def tag_test(request):
    return render(request, 'tag_test.html', {'example' : [2, 4, 6]})


def blog_search(request):
    current_time =timezone.now()
    posts = Post.objects.filter(published_date__lte=current_time, status=True)
    if request.method == "GET":
        if result := request.GET.get('s'):
            posts = posts.filter(Q(title__icontains=result) | Q(content__icontains=result))
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

blog/templates/blog/blog-home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% load functions %}
{% load humanize %}

        <div class="page-title wb">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <h2> All Posts </h2>
                    </div><!-- end col -->
                    <div class="col-lg-4 col-md-4 col-sm-12 hidden-xs-down hidden-sm-down">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url "mysite:index" %}">Home</a></li>
                            <li class="breadcrumb-item">Blog</li>
                            {% comment %} <li class="breadcrumb-item active">Food</li> {% endcomment %}
                        </ol>
                    </div><!-- end col -->                    
                </div><!-- end row -->
            </div><!-- end container -->
        </div><!-- end page-title -->

        <section class="section wb">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
                        <div class="page-wrapper">
                            <div class="blog-list clearfix">
                                {% for post in posts %}
                                    <div class="blog-box row mb-4">
                                        <div class="col-md-4">
                                            
                                            <div class="post-media">
                                                <a href="{% url "blog:single-blog" slug=post.slug %}" title="">
                                                    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
                                                    <div class="hovereffect"></div>
                                                </a>
                                            </div><!-- end media -->
                                        </div><!-- end col -->

                                        <div class="blog-meta big-meta col-md-8">
                                            <h4><a href="{% url "blog:single-blog" slug=post.slug %}" title="">{{post.title}}</a></h4>
                                            <p>{{post.content|truncatewords:30}}</p>
                                                <small><a href="{% url "blog:tag-page" tag_name=post.tag.name %}" title="">{{post.tag.name}}</a></small>
                                            <small>{{post.published_date|date:"d M Y"}}</small>
                                            <small><a href="{% url "blog:author-page" author_username=post.author.username %}" title="">by {{post.author.username}}</a></small>
                                            <a>{{post.view_count|apnumber}} <i class="fa fa-eye"></i></a>

                                            <div class="tag-cloud-single mt-4">
                                                <span>Categories</span>
                                                {% for cat in post.category.all|slice:":4" %}
                                                    <small><a href="{% url "blog:category-page" category_name=cat.name %}" title="">{{cat.name}}</a></small>
                                                {% endfor %}
            
                                            </div><!-- end meta -->

                                        </div><!-- end meta -->
                                    </div><!-- end blog-box -->
                                    <hr>
                                {% endfor %}

                                <hr class="invis">

                            </div><!-- end blog-list -->
                        </div><!-- end page-wrapper -->

                        <hr class="invis">

                        <div class="row">
                            <div class="col-md-12">
                                <nav aria-label="Page navigation">
                                    {% if posts.has_other_pages %}
                                        <ul class="pagination justify-content-start">

                                            {% if posts.has_previous %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a>
                                                </li>
                                            {% endif %}

                                            {% for i in page_range %}
                                                {% if posts.number == i %}
                                                    <li class="page-item primary"><a class="page-link" href="?page={{i}}">--{{ i }}--</a></li>
                                                {% else %}
                                                    <li class="page-item"><a class="page-link" href="?page={{i}}">{{ i }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if posts.has_next %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    {% endif %}
                                </nav>

                            </div><!-- end col -->
                        </div><!-- end row -->
                    </div><!-- end col -->

                    <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
                        <div class="sidebar">
                            {% include "blog/blog-search.html" %}
                            <div class="widget">
                                <h2 class="widget-title">Recent Posts</h2>
                                {% recent_posts %}
                            </div><!-- end widget -->


                            <div class="widget">
                                <h2 class="widget-title">Popular Categories</h2>
                                {% popular_categories %}
                            </div><!-- end widget -->

                        </div><!-- end sidebar -->
                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end container -->
        </section>
{% endblock content %}

blog/templates/blog/blog-search.html
<div class="widget">
    <h2 class="widget-title">Search</h2>
    <form class="form-inline search-form" method="GET" action="{% url "blog:blog-search" %}" >
        <div class="form-group">
            <input name='s' type="text" class="form-control" placeholder="Search on the site">
        </div>
        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
    </form>
</div><!-- end widget -->

blog/templates/blog/pop_category.html
<div class="link-widget">
    <ul>
        {% for category in categories %}
            <li><a href="{% url "blog:category-page" category_name=category.name %}">{{ category.name }}<span>({{category.category_count}})</span></a></li>
        {% endfor %}
    </ul>
</div><!-- end link-widget -->

blog/templates/blog/pop_posts.html
{% load static %}

<h2 class="widget-title">Popular Posts</h2>
<div class="blog-list-widget">
    <div class="list-group">
        {% for post in popular_posts %}
            <a href="{% url "blog:single-blog" slug=post.slug %}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="w-100 justify-content-between">
                    <img src="{{ post.image.url}}" alt="" class="img-fluid float-left">
                    <h5 class="mb-1">{{ post.title }}</h5>
                    <span class="rating">
                        views ({{ post.view_count }})
                    </span>
                </div>
            </a>
        {% endfor %}
    </div>
</div><!-- end blog-list -->

blog/templates/blog/recent_posts.html
{% load humanize %}
<div class="blog-list-widget">
    <div class="list-group">

        {% for post in recent_posts %}
            <a href="{% url "blog:single-blog" slug=post.slug %}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="w-100 justify-content-between">
                    <img src="{{post.image.url}}" alt="" class="img-fluid float-left">
                    <h5 class="mb-1">{{post.title}}</h5>
                    <small>{{post.published_date|naturaltime}}</small>
                </div>
            </a>
        {% endfor %}

    </div>
</div><!-- end blog-list -->