blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.home_blog, name='home-blog'),
    path('category/<str:category_name>/', views.home_blog, name='category-page'),
    path('tag/<str:tag_name>/', views.home_blog, name='tag-page'),
    path('author/<str:author_username>/', views.home_blog, name='author-page'),
    path('search/', views.blog_search, name='blog-search'),
    path('tag_test/', views.tag_test),
    path('<slug:slug>/', views.single_blog, name='single-blog'),



]

core/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from mysite.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog" : BlogSitemap,
}


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('mysite.urls')),
    path('blog/', include('blog.urls')),
    path("accounts/", include("users.urls")),
    path(
    "sitemap.xml",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",
),

    path('robots.txt', include('robots.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.urls import path
from mysite import views

app_name = 'mysite'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('sitemap/', views.sitemap, name='sitemap'),
    path('subscribe/', views.subscibe, name='subscibe'),
    path('test2/', views.test2, name='test2'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from core import settings
from users.views import CustomLogoutView, CustomLoginView
from users.views import signup_view

app_name = "users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name="logout"),
    path("signup/", signup_view, name="signup")

]

templates/base.html
{% load static %}
{% load functions%}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Site Metas -->
    <title>Cloapedia - Stylish Magazine Blog Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">
    
    <!-- Design fonts -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,400i,500,700" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700,900" rel="stylesheet"> 

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- FontAwesome Icons core CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'style.css' %}" rel="stylesheet">

    <!-- Responsive styles for this template -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

    <!-- Colors for this template -->
    <link href="{% static 'css/colors.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    

</head>
<body>

    <!-- LOADER -->
    <div id="preloader">
        <img class="preloader" src="{% static 'images/loader.gif' %}" alt="">
    </div><!-- end loader -->
    <!-- END LOADER -->

    <div id="wrapper">
        <div class="collapse top-search" id="collapseExample">
            <div class="card card-block">
                <div class="newsletter-widget text-center">
                    <form class="form-inline">
                        <input type="text" class="form-control" placeholder="What you are looking for?">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    </form>
                </div><!-- end newsletter -->
            </div>
        </div><!-- end top-search -->

        <div class="topbar-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-6 hidden-xs-down">

                    </div><!-- end col -->

                    <div class="col-lg-4 hidden-md-down">
                        <div class="topmenu text-center">


                            {% comment %} {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %} {% endcomment %}

                            <ul class="list-inline">
                                {% if not request.user.is_authenticated %}
                                    <li class="list-inline-item"><a href="{% url "users:login" %}"><i class="fa fa-star"></i> Loggin</a></li>
                                    <li class="list-inline-item"><a href="{% url "users:signup" %}"><i class="fa fa-bolt"></i> SignUp</a></li>
                                {% else %}
                                    <li class="list-inline-item"><a href="{% url 'mysite:index' %}"><i class="fa fa-star"></i> Logged is as {{request.user.username}}</a></li>
                                    <li class="list-inline-item"><a href="{% url "users:logout" %}"><i class="fa fa-bolt"></i> Logout</a></li>
                                {% endif %}

                                <li class="list-inline-item"><a href="{% url "mysite:contact" %}"><i class="fa fa-user-circle-o"></i> Contact Us</a></li>
                            </ul><!-- end ul -->
                        </div><!-- end topmenu -->
                    </div><!-- end col -->

                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">

                    </div><!-- end col -->
                </div><!-- end row -->
            </div><!-- end header-logo -->
        </div><!-- end topbar -->

        <div class="header-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="logo">
                            <a href="index.html"><img src="{% static 'images/logo.png' %}" alt=""></a>
                        </div><!-- end logo -->
                    </div>
                </div><!-- end row -->
            </div><!-- end header-logo -->
        </div><!-- end header -->

        <header class="header">
            <div class="container">
                <nav class="navbar navbar-inverse navbar-toggleable-md">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#cloapediamenu" aria-controls="cloapediamenu" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-md-center" id="cloapediamenu">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link color-pink-hover" href="{% url "mysite:index" %}">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link color-red-hover" href="{% url "blog:home-blog" %}">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link color-aqua-hover" href="{% url "mysite:about" %}">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link color-green-hover" href="{% url "mysite:sitemap" %}">Archives</a>
                            </li>  
                        </ul>
                    </div>
                </nav>
            </div><!-- end container -->
        </header><!-- end header -->

{% block content %}{% endblock content %}


<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                    <h2 class="widget-title">Recent Posts</h2>
                    {% recent_posts %}
                </div><!-- end widget -->
            </div><!-- end col -->

            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                    {% popular_posts %}
                </div><!-- end widget -->
            </div><!-- end col -->

            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <div class="widget">
                    <h2 class="widget-title">Popular Categories</h2>
                    {% popular_categories %}
                </div><!-- end widget -->
            </div><!-- end col -->
        </div><!-- end row -->

        <hr class="invis1">

        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="widget">
                    <div class="footer-text text-center">
                        <a href="index.html"><img src="{% static 'images/flogo.png' %}  " alt="" class="img-fluid"></a>
                        <p>Cloapedia is a personal blog for handcrafted, cameramade photography content, fashion styles from independent creatives around the world.</p>
                        <div class="social">
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>              
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fa fa-instagram"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                            <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a>
                        </div>

                        <hr class="invis">

                        <div class="newsletter-widget text-center">
                            <form class="form-inline" method="POST" action="{% url "mysite:subscibe" %}">
                                {% csrf_token %}
                                <input name="email" type="text" class="form-control" placeholder="Enter your email address">
                                <button type="submit" class="btn btn-primary">Subscribe <i class="fa fa-envelope-open-o"></i></button>
                            </form>
                        </div><!-- end newsletter -->
                    </div><!-- end footer-text -->
                </div><!-- end widget -->
            </div><!-- end col -->
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <br>
                <div class="copyright">&copy; Cloapedia. Design: <a href="http://html.design">HTML Design</a>.</div>
            </div>
        </div>
    </div><!-- end container -->
</footer><!-- end footer -->

<div class="dmtop">Scroll to Top</div>

</div><!-- end wrapper -->

<!-- Core JavaScript
================================================== -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/tether.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

<!--===============================================================================================-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    {% for msg in messages %}
        Swal.fire('{{ msg }}');
    {% endfor %}
</script>

</body>
</html>

templates/tag_test.html
{% load functions %}
{% posts as posts%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">   
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% for post in posts %}
        <h1>{{ post.title}}</h1>
        <p>{{ post.content|snippet:20 }}</p>
        {% endfor %}
    </body>
</html>

templates/test.html
{% for key, value in archive.items %}
    <p>{{key}}</p>
    {% for post in value %}
        <h2>{{post.title}}</h2>
        <p>{{ post.content}}</p>
    {% endfor %}
{% endfor %}

templates/test2.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <form action="{% url "mysite:test2" %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Submit</button>
        </form>
    </body>
</html>